### ISSUE TITLE
Skip or offset or change cursor implementation

### ISSUE THREAD

**Issue by adamofig** [nitxiodev/py-mongonnator#4]
Awesome job with this library, what I would like to do,  is to use it in an API, the frontend will call this paginate method but set the offset or skip, in order to get the pages on demand, is this possible?  I don't see an option to do that.

**Comment by nitxiodev** [comment]
Hi @adamofig,

Thank you so much! :smile: 

If I understand correctly, what you pretend is given a page number, retrieve the content for that page right?

If that is the case, disgracefully, this library won't fit your use case because it implements `cursor-based pagination`, and what you are looking for is called `offset-pagination`, which can be done seamlessly by using the `skip`/`limit` methods in your query:

```python
db.my_secret_collection.find({}).limit(5)  # page 1 - 5 docs per page
db.my_secret_collection.find({}).skip(5).limit(5)  # page 2 - 5 docs per page
...
```
This library works for those cases where you don't need to jump directly to a specific page. For example, imagine you have implemented a component to do an `infinite-scroll` when the user reaches the end of the page. In that scenario, you just need the "pointer" to the next page instead of the page number.
